services:
  postgres:
    image: postgres:15-alpine
    container_name: excepio-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gzQFyXv95B2@Xe
      POSTGRES_DB: excepio
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
